#ifndef CMOCKA_CONFIG_H_
#define CMOCKA_CONFIG_H_

#define HAVE_SIGNAL_H
#define HAVE_CLOCK_GETTIME_REALTIME
#define HAVE_STRUCT_TIMESPEC
#define CMOCKA_PLATFORM_INCLUDE

#endif /* CMOCKA_CONFIG_H_ */
